const state={i:0,time:90,risk:18,info:28,battery:63,mobility:78,network:'NORMAL',companion:0,supplies:0,route:'high',stress:14,flags:{},history:[],feedback:null};
const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));let visualBindings=[];
function showOpening(){if($('opening'))return;const o=document.createElement('section');o.id='opening';o.innerHTML='<div class="opening-bg"></div><div class="opening-copy"><div class="opening-kicker">BEFORE THE WARNING</div><h1>棰勮涔嬪墠</h1><div class="opening-en">BEFORE THE WARNING</div><p>鐪熸鏀瑰彉缁撴灉鐨勶紝<br>寰€寰€鍙戠敓鍦ㄧ伨瀹冲埌鏉ヤ箣鍓嶃€?/p><button id="startFilm">杩涘叆妯℃嫙</button></div>';document.body.prepend(o);setTimeout(()=>o.classList.add('opening-title'),1200);setTimeout(()=>o.classList.add('opening-line','opening-ready'),2500);$('startFilm').onclick=()=>{o.classList.add('opening-out');setTimeout(()=>o.remove(),700)}}
function ensurePhoto(){const c=$('cinema');let p=$('scenePhoto');if(!p){p=document.createElement('img');p.id='scenePhoto';p.className='scene-photo';c.prepend(p)}return p}
function renderPhoto(){const p=ensurePhoto(),a=visualBindings[state.i%visualBindings.length];if(!a)return;p.src=a.file+'?v=final-5';p.alt='鐏惧鍦烘櫙';p.onerror=()=>{p.style.display='none';$('cinema').classList.add('visual-fallback');$('cinema').setAttribute('data-fallback','鐏惧鍦烘櫙 路 '+(SCENARIOS[state.i].location||'鏍″洯'))};p.onload=()=>{p.style.display='block';$('cinema').classList.remove('visual-fallback')}}
function infoText(){if(state.info>=60)return '宸茬‘璁わ細瀛︽牎閫氱煡宸叉洿鏂帮紝宸ヤ綔浜哄憳姝ｅ湪寮曞楂樺璺嚎銆?;if(state.info>=40)return '宸茬煡锛氶檷闆ㄥ寮猴紝閮ㄥ垎閬撹矾绉按锛涘悓瀛︽秷鎭皻鏈畬鍏ㄧ‘璁ゃ€?;return '灏氭湭纭锛氫笢闂ㄦ槸鍚﹀皝闂€佸湴閾佹槸鍚︾户缁繍琛屻€?}
function showFeedback(c,nextIndex){const box=document.createElement('section');box.className='choice-feedback';box.innerHTML=`<div class="feedback-kicker">浣犵殑閫夋嫨</div><h2>${c[1]}</h2><div class="feedback-time">鏃堕棿鎺ㄨ繘 路 ${Math.max(1,Math.round(Math.abs(Number((c[3]||'').match(/time:([-\d]+)/)?.[1]||3))))} 鍒嗛挓</div><p>鐜板満鍙樺寲锛?{state.risk>55?'闆ㄥ娍鍜岀Н姘寸户缁彂灞曪紝鍘熻矾绾块渶瑕侀噸鏂板垽鏂€?:'浣犺幏寰椾簡鏂扮殑鐜板満淇℃伅锛屼笅涓€姝ヨ鍔ㄧ獥鍙ｄ粛鐒跺瓨鍦ㄣ€?}</p><p class="feedback-impact">褰卞搷锛氫俊鎭笌璺嚎鐘舵€佸凡鏇存柊銆?/p><button id="continueFeedback">缁х画</button>`;document.body.append(box);$('continueFeedback').onclick=()=>{box.remove();render()}}
function render(){const sc=SCENARIOS[state.i];$('sceneNo').textContent=`鍦烘櫙 ${state.i+1}`;$('location').textContent=sc.location||'鏍″洯';$('caption').textContent=sc.description||'鐜板満鎯呭喌姝ｅ湪鍙樺寲銆?;$('intel').innerHTML=`<strong>褰撳墠鎯呭喌</strong><br>${infoText()}<br><small>椋庨櫓绛夌骇锛?{state.risk<35?'浣?:state.risk<60?'杈冮珮':state.risk<80?'楂?:'鏋侀珮'} 路 閫氳锛?{state.network}</small>`;$('time').textContent=state.time;$('risk').textContent=state.risk<35?'浣?:state.risk<60?'杈冮珮':state.risk<80?'楂?:'鏋侀珮';$('battery').textContent=Math.round(state.battery);$('infoVal').textContent=Math.round(state.info);$('networkVal').textContent=state.network;$('mobilityVal').textContent=Math.round(state.mobility);$('companionVal').textContent=state.companion?'宸茶仈绯?:'鏈仈绯?;$('suppliesVal').textContent=`${state.supplies}/3`;$('infoBar').style.width=state.info+'%';$('mobilityBar').style.width=state.mobility+'%';$('timeLabel').textContent=`T-${String(state.time).padStart(2,'0')}:00`;$('choices').innerHTML=(sc.choices||[]).map((c,n)=>`<button class="choice" data-n="${n}"><b>${String.fromCharCode(65+n)} ${state.i===0?['鏍稿疄瀹樻柟淇℃伅','鑱旂郴瀹朵汉鍜屽鍙?,'鍏堝幓椋熷爞'][n]||c[1]:c[1]}</b><span>${c[2]||''}</span></button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(sc.choices[+b.dataset.n]));renderPhoto()}
function apply(raw){for(const p of(raw||'').split(',')){const[k,v]=p.split(':');if(k==='route')state.route=v;else if(k==='network')state.network=Number(v)>0?'CONGESTED':'NORMAL';else if(k in state&&typeof state[k]==='number')state[k]+=Number(v)}state.risk=clamp(state.risk,0,100);state.info=clamp(state.info,0,100);state.battery=clamp(state.battery,0,100);state.time=clamp(state.time,0,90)}
function choose(c){state.history.push({scene:state.i,choice:c[1],time:state.time});apply(c[3]);if(c[4])state.flags[c[4]]=true;showFeedback(c,Math.min(state.i+1,SCENARIOS.length-1))}
function finish(){setTimeout(()=>{document.querySelector('.recap').classList.add('show');$('recapText').innerHTML='<h3>妯℃嫙缁撴潫</h3><p>浣犵殑閫夋嫨鏀瑰彉浜嗚矾绾裤€佷俊鎭川閲忓拰閬块櫓鏃堕棿銆?/p><p>鍐崇瓥鏁堢巼 路 淇℃伅鍒╃敤鑳藉姏 路 椋庨櫓鎺у埗鑳藉姏 路 鏃堕棿绠＄悊</p>';$('eventlog').innerHTML=state.history.map((x,n)=>`<div>绗?${n+1} 娆″喅绛?路 ${x.choice}</div>`).join('')},300)}
fetch('data/visual-bindings.json?v=final-5').then(r=>r.json()).then(x=>{visualBindings=x;showOpening();render()}).catch(()=>{showOpening();render()});$('undo').onclick=()=>{if(state.history.length){state.history.pop();state.i=Math.max(0,state.i-1);render()}};$('restart').onclick=()=>location.reload();

