const state={i:0,time:90,risk:18,info:28,battery:63,mobility:78,network:'NORMAL',companion:0,supplies:0,route:'high',stress:14,flags:{},delayed:[],log:[],history:[]};
const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));let visualBindings=[];
function showOpening(){if(document.getElementById('opening'))return;const o=document.createElement('section');o.id='opening';o.innerHTML='<div class="opening-bg"></div><div class="opening-copy"><div class="opening-kicker">BEFORE THE WARNING</div><h1>预警之前</h1><div class="opening-en">BEFORE THE WARNING</div><p>真正改变结果的，<br>往往发生在灾害到来之前。</p><button id="startFilm">进入模拟</button></div><button class="opening-corner" id="openingTeacherBtn">教师模式</button>';document.body.prepend(o);setTimeout(()=>o.classList.add('opening-title'),2200);setTimeout(()=>o.classList.add('opening-line'),4000);setTimeout(()=>o.classList.add('opening-ready'),5500);setTimeout(()=>o.classList.add('opening-title','opening-line','opening-ready'),7000);$('startFilm').onclick=()=>{o.classList.add('opening-out');setTimeout(()=>o.remove(),700)}}
function renderPhoto(){const sc=SCENARIOS[state.i],a=visualBindings.find(x=>x.visualAssetId===sc.image)||visualBindings.find(x=>x.scene===sc.id),p=document.getElementById('scenePhoto');if(!p||!a)return;p.src=a.file+'?v=final-4';p.alt=sc.location;p.onerror=()=>p.removeAttribute('src')}
function render(){const sc=SCENARIOS[state.i];$('sceneNo').textContent=`${sc.time||'场景'} · ${sc.location}`;$('location').textContent=sc.location;$('caption').textContent=sc.description;$('intel').textContent=state.risk>65?'水位正在上升，原路线风险增加。':state.info>65?'已有可靠信息可以交叉确认。':'信息仍不完整。';$('time').textContent=state.time;$('risk').textContent=state.risk<35?'低':state.risk<60?'较高':state.risk<80?'高':'极高';$('battery').textContent=Math.round(state.battery);$('infoVal').textContent=Math.round(state.info);$('networkVal').textContent=state.network;$('mobilityVal').textContent=Math.round(state.mobility);$('companionVal').textContent=state.companion?'已联系':'未联系';$('suppliesVal').textContent=`${state.supplies}/3`;$('infoBar').style.width=state.info+'%';$('mobilityBar').style.width=state.mobility+'%';$('timebar').style.width=((90-state.time)/90*100)+'%';$('timeLabel').textContent=`T-${String(state.time).padStart(2,'0')}:00`;$('flood').style.opacity=.12+state.risk/130;$('safeRoute').style.opacity=state.route==='high'?1:.35;$('metroRoute').style.opacity=state.route==='metro'?1:.35;$('dormRoute').style.opacity=state.route==='dorm'?1:.35;$('choices').innerHTML=(sc.choices||[]).map((c,n)=>`<button class="choice" data-n="${n}"><b>${String.fromCharCode(65+n)} ${c[1]}</b><span>${c[2]}</span></button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(sc.choices[+b.dataset.n]));$('feed').innerHTML=state.log.slice(-6).map(x=>`<li>${x}</li>`).join('');if(state.i===SCENARIOS.length-1)finish();renderPhoto()}
function apply(raw){for(const p of(raw||'').split(',')){const[k,v]=p.split(':');if(k==='route')state.route=v;else if(k==='network')state.network=Number(v)>0?'CONGESTED':'NORMAL';else if(k in state&&typeof state[k]==='number')state[k]+=Number(v)}state.risk=clamp(state.risk,0,100);state.info=clamp(state.info,0,100);state.battery=clamp(state.battery,0,100);state.time=clamp(state.time,0,90)}
function choose(c){state.history.push(JSON.parse(JSON.stringify(state)));if(c[0]==='finish'){finish();return}apply(c[3]);if(c[4])state.flags[c[4]]=true;state.log.push(`${SCENARIOS[state.i].time||'事件'} · ${c[1]}`);state.i++;render()}
function finish(){document.querySelector('.recap').classList.add('show');$('recapText').innerHTML='<h3>灾害决策复盘</h3><p>真正改变结果的，往往发生在灾害到来之前。</p>';$('eventlog').innerHTML=state.log.map(x=>`<div>${x}</div>`).join('')}
fetch('data/visual-bindings.json?v=final-4').then(r=>r.json()).then(x=>{visualBindings=x;showOpening();render()}).catch(()=>{showOpening();render()});$('undo').onclick=()=>{if(state.history.length){Object.assign(state,state.history.pop());state.i=Math.max(0,state.i-1);render()}};$('restart').onclick=()=>location.reload();
