const state={i:0,time:90,risk:18,info:28,battery:63,mobility:78,network:'NORMAL',companion:0,supplies:0,route:'high',stress:14,flags:{},history:[],feedback:null};
const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));let visualBindings=[];
function showOpening(){if($('opening'))return;const o=document.createElement('section');o.id='opening';o.innerHTML='<div class="opening-bg"></div><div class="opening-copy"><div class="opening-kicker">BEFORE THE WARNING</div><h1>预警之前</h1><div class="opening-en">BEFORE THE WARNING</div><p>真正改变结果的，<br>往往发生在灾害到来之前。</p><button id="startFilm">进入模拟</button></div>';document.body.prepend(o);setTimeout(()=>o.classList.add('opening-title'),1200);setTimeout(()=>o.classList.add('opening-line','opening-ready'),2500);$('startFilm').onclick=()=>{o.classList.add('opening-out');setTimeout(()=>o.remove(),700)}}
function ensurePhoto(){const c=$('cinema');let p=$('scenePhoto');if(!p){p=document.createElement('img');p.id='scenePhoto';p.className='scene-photo';c.prepend(p)}return p}
function renderPhoto(){const p=ensurePhoto(),a=visualBindings[state.i%visualBindings.length];if(!a)return;p.src=a.file+'?v=final-5';p.alt='灾害场景';p.onerror=()=>{p.style.display='none';$('cinema').classList.add('visual-fallback');$('cinema').setAttribute('data-fallback','灾害场景 · '+(SCENARIOS[state.i].location||'校园'))};p.onload=()=>{p.style.display='block';$('cinema').classList.remove('visual-fallback')}}
function infoText(){if(state.info>=60)return '已确认：学校通知已更新，工作人员正在引导高处路线。';if(state.info>=40)return '已知：降雨增强，部分道路积水；同学消息尚未完全确认。';return '尚未确认：东门是否封闭、地铁是否继续运行。'}
function showFeedback(c){const box=document.createElement('section');box.className='choice-feedback';box.innerHTML=`<div class="feedback-kicker">你的选择</div><h2>${c[1]}</h2><div class="feedback-time">时间推进 · ${Math.max(1,Math.round(Math.abs(Number((c[3]||'').match(/time:([-\d]+)/)?.[1]||3))))} 分钟</div><p>现场变化：${state.risk>55?'雨势和积水继续发展，原路线需要重新判断。':'你获得了新的现场信息，下一步行动窗口仍然存在。'}</p><p class="feedback-impact">影响：信息与路线状态已更新。</p><button id="continueFeedback">继续</button>`;document.body.append(box);$('continueFeedback').onclick=()=>{box.remove();render()}}
function render(){const sc=SCENARIOS[state.i];$('sceneNo').textContent=`场景 ${state.i+1}`;$('location').textContent=sc.location||'校园';$('caption').textContent=sc.description||'现场情况正在变化。';$('intel').innerHTML=`<strong>当前情况</strong><br>${infoText()}<br><small>风险等级：${state.risk<35?'低':state.risk<60?'较高':state.risk<80?'高':'极高'} · 通讯：${state.network}</small>`;$('time').textContent=state.time;$('risk').textContent=state.risk<35?'低':state.risk<60?'较高':state.risk<80?'高':'极高';$('battery').textContent=Math.round(state.battery);$('infoVal').textContent=Math.round(state.info);$('networkVal').textContent=state.network;$('mobilityVal').textContent=Math.round(state.mobility);$('companionVal').textContent=state.companion?'已联系':'未联系';$('suppliesVal').textContent=`${state.supplies}/3`;$('infoBar').style.width=state.info+'%';$('mobilityBar').style.width=state.mobility+'%';$('timeLabel').textContent=`T-${String(state.time).padStart(2,'0')}:00`;$('choices').innerHTML=(sc.choices||[]).map((c,n)=>`<button class="choice" data-n="${n}"><b>${String.fromCharCode(65+n)} ${state.i===0?['核实官方信息','联系家人和室友','先去食堂'][n]||c[1]:c[1]}</b><span>${c[2]||''}</span></button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(sc.choices[+b.dataset.n]));renderPhoto()}
function apply(raw){for(const p of(raw||'').split(',')){const[k,v]=p.split(':');if(k==='route')state.route=v;else if(k==='network')state.network=Number(v)>0?'CONGESTED':'NORMAL';else if(k in state&&typeof state[k]==='number')state[k]+=Number(v)}state.risk=clamp(state.risk,0,100);state.info=clamp(state.info,0,100);state.battery=clamp(state.battery,0,100);state.time=clamp(state.time,0,90)}
function choose(c){state.history.push({scene:state.i,choice:c[1],time:state.time});apply(c[3]);if(c[4])state.flags[c[4]]=true;showFeedback(c);if(state.i>=SCENARIOS.length-1)finish()}
function finish(){setTimeout(()=>{document.querySelector('.recap').classList.add('show');$('recapText').innerHTML='<h3>模拟结束</h3><p>你的选择改变了路线、信息质量和避险时间。</p><p>决策效率 · 信息利用能力 · 风险控制能力 · 时间管理</p>';$('eventlog').innerHTML=state.history.map((x,n)=>`<div>第 ${n+1} 次决策 · ${x.choice}</div>`).join('')},300)}
fetch('data/visual-bindings.json?v=final-5').then(r=>r.json()).then(x=>{visualBindings=x;showOpening();render()}).catch(()=>{showOpening();render()});$('undo').onclick=()=>{if(state.history.length){state.history.pop();state.i=Math.max(0,state.i-1);render()}};$('restart').onclick=()=>location.reload();
